# Generated by Django 5.2.7 on 2025-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_preview_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(help_text='PDF file', upload_to='tasks/files/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='preview',
            field=models.ImageField(help_text='Preview image (JPEG/PNG)', upload_to='tasks/previews/'),
        ),
    ]
