# Generated by Django 5.2.7 on 2025-11-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_is_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categories'},
        ),
    ]
