# Generated by Django 5.2.7 on 2025-11-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_meta_description_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('coloring', 'Раскраски'), ('tasks', 'Задания'), ('videos', 'Видео уроки')], default='coloring', help_text='Select the type of content this category belongs to', max_length=20),
        ),
    ]
