# Generated by Django 5.2.7 on 2025-11-11 15:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_title', models.CharField(default='Work faster with powerful tools', max_length=200)),
                ('home_page_subtitle', models.CharField(default='trendy application', max_length=200)),
                ('home_page_description', ckeditor.fields.RichTextField(blank=True, default='Laboris culpa ea incididunt dolore ipsum tempor duis&nbsp;do ullamco eiusmod officia magna ad id.')),
                ('home_page_button_text', models.CharField(default='Learn More', max_length=50)),
                ('most_popular_title', models.CharField(default='The most popular application 2021', max_length=200)),
                ('most_popular_description', ckeditor.fields.RichTextField(blank=True, default='Culpa non ex tempor qui nulla laborum. Laboris&nbsp;culpa ea incididunt dolore ipsum.')),
                ('features_section_title', models.CharField(default='See what you will get with us', max_length=200)),
                ('presentation_title', models.CharField(default='Watch our UI presentation', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 characters max)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (160 characters max)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords separated by commas', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
