# Generated by Django 5.2.7 on 2025-11-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='accent_color',
            field=models.CharField(default='#F0F0F0', help_text='Accent color in hex format (e.g., #F0F0F0)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='primary_color',
            field=models.CharField(default='#FF6B35', help_text='Primary color in hex format (e.g., #FF6B35)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='secondary_color',
            field=models.CharField(default='#2A363B', help_text='Secondary color in hex format (e.g., #2A363B)', max_length=7),
        ),
    ]
