# Generated by Django 5.2.7 on 2025-11-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_add_series_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['series_group', 'order', '-date'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
