# Generated by Django 5.2.7 on 2025-11-03 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Video description with rich text formatting'),
        ),
    ]
