# Generated by Django 5.2.7 on 2025-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_meta_description_video_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='large_preview',
            field=models.FileField(blank=True, help_text='Large preview file (MP4 or other video format)', null=True, upload_to='videos/large_previews/'),
        ),
    ]
