# Generated by Django 5.2.7 on 2025-11-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_fix_created_at'),
        ('categories', '0003_alter_category_options'),
        ('video', '0003_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adblock',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Advertising Block', 'verbose_name_plural': 'Advertising Blocks'},
        ),
        migrations.AlterField(
            model_name='adblock',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Category to link to (if content_type is 'category')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_blocks', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='adblock',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('category', 'Category')], default='category', help_text='Type of content this ad block links to', max_length=20),
        ),
        migrations.AlterField(
            model_name='adblock',
            name='video',
            field=models.ForeignKey(blank=True, help_text="Video to link to (if content_type is 'video')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_blocks', to='video.video'),
        ),
    ]
