# Generated by Django 5.2.7 on 2025-11-03 10:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_adblock_options_alter_adblock_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adblock',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Ad block description with rich text formatting'),
        ),
    ]
