# Generated by Django 5.2.7 on 2025-11-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_fix_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at']},
        ),
    ]
