# Generated by Django 5.2.7 on 2025-11-03 10:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_banner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Banner description with rich text formatting'),
        ),
    ]
