# Generated by Django 5.2.7 on 2025-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_add_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coloring',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coloring', 'verbose_name_plural': 'Colorings'},
        ),
        migrations.AlterField(
            model_name='coloring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coloring',
            name='file',
            field=models.FileField(help_text='PDF file', upload_to='coloring/files/'),
        ),
        migrations.AlterField(
            model_name='coloring',
            name='preview',
            field=models.ImageField(help_text='Preview image (JPEG/PNG)', upload_to='coloring/previews/'),
        ),
    ]
