# Generated by Django 5.2.7 on 2025-11-03 10:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_alter_coloring_options_alter_coloring_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloring',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Coloring description with rich text formatting'),
        ),
    ]
