# Generated by Django 5.2.7 on 2025-11-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_coloring_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloring',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (160 characters max)', max_length=160),
        ),
        migrations.AddField(
            model_name='coloring',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords separated by commas', max_length=255),
        ),
        migrations.AddField(
            model_name='coloring',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 characters max)', max_length=60),
        ),
    ]
