# Generated by Django 5.2.7 on 2025-11-03 10:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Subscription plan description with rich text formatting'),
        ),
    ]
